/*
* generated by Xtext
*/
package com.factmint.moka.eclipse.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MokaDSLStandaloneSetup extends MokaDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new MokaDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

