/*
 * generated by Xtext
 */
package com.factmint.moka.eclipse.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MokaDSLRuntimeModule extends com.factmint.moka.eclipse.xtext.AbstractMokaDSLRuntimeModule {

}
