/**
 * generated by Xtext
 */
package com.factmint.moka.eclipse.xtext.validation;

import com.factmint.moka.eclipse.xtext.validation.AbstractMokaDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MokaDSLValidator extends AbstractMokaDSLValidator {
}
