/*
 * generated by Xtext
 */
package com.factmint.moka.eclipse.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MokaDSLUiModule extends com.factmint.moka.eclipse.xtext.ui.AbstractMokaDSLUiModule {
	public MokaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
