/*
* generated by Xtext
*/
package com.factmint.moka.eclipse.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MokaDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/factmint/moka/eclipse/xtext/parser/antlr/internal/InternalMokaDSL.tokens");
	}
}
