/*
* generated by Xtext
*/
package com.factmint.moka.eclipse.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.factmint.moka.eclipse.xtext.services.MokaDSLGrammarAccess;

public class MokaDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MokaDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.factmint.moka.eclipse.xtext.parser.antlr.internal.InternalMokaDSLParser createParser(XtextTokenStream stream) {
		return new com.factmint.moka.eclipse.xtext.parser.antlr.internal.InternalMokaDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MokaDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MokaDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
